class LLMService:
    # LLM katmanını temsil eden servis sınıfı
    # Şimdilik örnek cevap döndürür, daha sonra gerçek API çağrısıyla değiştirilecektir

    def ask(self, prompt: str) -> str:
        # Geçici örnek cevap üretir
        return "This response was generated by the LLM layer."