version: "1.3.4"

endpoints:
  custom:
    - name: "CogniTwin"
      apiKey: "cognitwin"
      baseURL: "http://cognitwin-api:8011/v1/"
      models:
        default:
          - "cognitwin-student-llm"
        fetch: false
      modelDisplayLabel: "CogniTwin Student"

    - name: "CogniTwin Developer"
      apiKey: "cognitwin"
      baseURL: "http://cognitwin-api:8011/v1/"
      models:
        default:
          - "cognitwin-developer"
        fetch: false
      modelDisplayLabel: "CogniTwin Developer"

    - name: "CogniTwin Scrum"
      apiKey: "cognitwin"
      baseURL: "http://cognitwin-api:8011/v1/"
      models:
        default:
          - "cognitwin-scrum"
        fetch: false
      modelDisplayLabel: "CogniTwin Scrum Master"

    - name: "CogniTwin Product Owner"
      apiKey: "cognitwin"
      baseURL: "http://cognitwin-api:8011/v1/"
      models:
        default:
          - "cognitwin-product-owner"
        fetch: false
      modelDisplayLabel: "CogniTwin Product Owner"

    - name: "CogniTwin Composer"
      apiKey: "cognitwin"
      baseURL: "http://cognitwin-api:8011/v1/"
      models:
        default:
          - "cognitwin-composer"
        fetch: false
      modelDisplayLabel: "CogniTwin Composer"

    - name: "CogniTwin HR"
      apiKey: "cognitwin"
      baseURL: "http://cognitwin-api:8011/v1/"
      models:
        default:
          - "cognitwin-hr"
        fetch: false
      modelDisplayLabel: "CogniTwin HR Recruiter"